# Generated by Django 4.1 on 2023-01-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='balls',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='images/'),
        ),
    ]
